version: 2
updates:
  - package-ecosystem: gomod
    directory: "/provider"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10
    reviewers:
      - pulumi/platform-integrations
    labels:
      - dependencies
      - dependabot
