provider: snowflake
major-version: 2
esc:
    enabled: true
env:
    SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
    SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
    SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
    SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
    SNOWFLAKE_REGION: ${{ secrets.SNOWFLAKE_REGION }}
makeTemplate: bridged
team: ecosystem
license:
    ignore:
        # These projects don't have a LICENSE file, but do say mention (in README.md) that
        # they are under Apache-2.0.
        - github.com/apache/arrow
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
