// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.snowflake.ApiIntegrationGitRepositoryOauth2Args;
import com.pulumi.snowflake.Utilities;
import com.pulumi.snowflake.inputs.ApiIntegrationGitRepositoryOauth2State;
import com.pulumi.snowflake.outputs.ApiIntegrationGitRepositoryOauth2DescribeOutput;
import com.pulumi.snowflake.outputs.ApiIntegrationGitRepositoryOauth2ShowOutput;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * &gt; **Caution: Preview Feature** This feature is considered a preview feature in the provider, regardless of the state of the resource in Snowflake. We do not guarantee its stability. It will be reworked and marked as a stable feature in future releases. Breaking changes are expected, even without bumping the major version. To use this feature, add the relevant feature name to `previewFeaturesEnabled` field in the provider configuration. Please always refer to the Getting Help section in our Github repo to best determine how to get help for your questions.
 * 
 * Resource used to manage API integration Git Repository OAuth2 objects. For more information, check [api integration documentation](https://docs.snowflake.com/en/sql-reference/sql/create-api-integration).
 * 
 * ## Example Usage
 * 
 * &gt; **Note** Instead of using fully_qualified_name, you can reference objects managed outside Terraform by constructing a correct ID, consult identifiers guide.
 * &lt;!-- TODO(SNOW-1634854): include an example showing both methods--&gt;
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.snowflake.ApiIntegrationGitRepositoryOauth2;
 * import com.pulumi.snowflake.ApiIntegrationGitRepositoryOauth2Args;
 * import java.util.ArrayList;
 * import java.util.Arrays;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         // basic resource
 *         var basic = new ApiIntegrationGitRepositoryOauth2("basic", ApiIntegrationGitRepositoryOauth2Args.builder()
 *             .name("git_repository_oauth2_integration")
 *             .oauthAuthorizationEndpoint("https://gitlab.com/oauth/authorize")
 *             .oauthTokenEndpoint("https://gitlab.com/oauth/token")
 *             .oauthClientId("my-client-id")
 *             .oauthClientSecret("my-client-secret")
 *             .apiAllowedPrefixes("https://gitlab.com/my-org/")
 *             .enabled(true)
 *             .build());
 * 
 *         // complete resource
 *         var complete = new ApiIntegrationGitRepositoryOauth2("complete", ApiIntegrationGitRepositoryOauth2Args.builder()
 *             .name("git_repository_oauth2_integration_complete")
 *             .oauthAuthorizationEndpoint("https://gitlab.com/oauth/authorize")
 *             .oauthTokenEndpoint("https://gitlab.com/oauth/token")
 *             .oauthClientId("my-client-id")
 *             .oauthClientSecret("my-client-secret")
 *             .oauthAccessTokenValidity(3600)
 *             .oauthRefreshTokenValidity(86400)
 *             .oauthAllowedScopes("read_repository")
 *             .oauthUsername("my-git-user")
 *             .apiAllowedPrefixes("https://gitlab.com/my-org/")
 *             .apiBlockedPrefixes("https://gitlab.com/my-org/private-repo/")
 *             .enabled(true)
 *             .comment("Example Git Repository OAuth2 integration")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * &gt; **Note** If a field has a default value, it is shown next to the type in the schema.
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import snowflake:index/apiIntegrationGitRepositoryOauth2:ApiIntegrationGitRepositoryOauth2 example &#39;&#34;&lt;name&gt;&#34;&#39;
 * ```
 * 
 */
@ResourceType(type="snowflake:index/apiIntegrationGitRepositoryOauth2:ApiIntegrationGitRepositoryOauth2")
public class ApiIntegrationGitRepositoryOauth2 extends com.pulumi.resources.CustomResource {
    /**
     * Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
     * 
     */
    @Export(name="apiAllowedPrefixes", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> apiAllowedPrefixes;

    /**
     * @return Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
     * 
     */
    public Output<List<String>> apiAllowedPrefixes() {
        return this.apiAllowedPrefixes;
    }
    /**
     * Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
     * 
     */
    @Export(name="apiBlockedPrefixes", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> apiBlockedPrefixes;

    /**
     * @return Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
     * 
     */
    public Output<Optional<List<String>>> apiBlockedPrefixes() {
        return Codegen.optional(this.apiBlockedPrefixes);
    }
    /**
     * Specifies a comment for the integration.
     * 
     */
    @Export(name="comment", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> comment;

    /**
     * @return Specifies a comment for the integration.
     * 
     */
    public Output<Optional<String>> comment() {
        return Codegen.optional(this.comment);
    }
    /**
     * Outputs the result of `DESCRIBE API INTEGRATION` for the given integration.
     * 
     */
    @Export(name="describeOutputs", refs={List.class,ApiIntegrationGitRepositoryOauth2DescribeOutput.class}, tree="[0,1]")
    private Output<List<ApiIntegrationGitRepositoryOauth2DescribeOutput>> describeOutputs;

    /**
     * @return Outputs the result of `DESCRIBE API INTEGRATION` for the given integration.
     * 
     */
    public Output<List<ApiIntegrationGitRepositoryOauth2DescribeOutput>> describeOutputs() {
        return this.describeOutputs;
    }
    /**
     * Specifies whether this API integration is enabled or disabled.
     * 
     */
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enabled;

    /**
     * @return Specifies whether this API integration is enabled or disabled.
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }
    /**
     * Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
     * 
     */
    @Export(name="fullyQualifiedName", refs={String.class}, tree="[0]")
    private Output<String> fullyQualifiedName;

    /**
     * @return Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
     * 
     */
    public Output<String> fullyQualifiedName() {
        return this.fullyQualifiedName;
    }
    /**
     * Specifies the identifier (i.e. name) for the integration. This value must be unique in your account. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Specifies the identifier (i.e. name) for the integration. This value must be unique in your account. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Specifies the validity period (in seconds) for the OAuth 2.0 access token.
     * 
     */
    @Export(name="oauthAccessTokenValidity", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> oauthAccessTokenValidity;

    /**
     * @return Specifies the validity period (in seconds) for the OAuth 2.0 access token.
     * 
     */
    public Output<Optional<Integer>> oauthAccessTokenValidity() {
        return Codegen.optional(this.oauthAccessTokenValidity);
    }
    /**
     * Specifies a list of scopes to use when making a request from the OAuth by a role with USAGE on the integration. Valid values are (case-insensitive): `readApi` | `readRepository` | `writeRepository`.
     * 
     */
    @Export(name="oauthAllowedScopes", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> oauthAllowedScopes;

    /**
     * @return Specifies a list of scopes to use when making a request from the OAuth by a role with USAGE on the integration. Valid values are (case-insensitive): `readApi` | `readRepository` | `writeRepository`.
     * 
     */
    public Output<Optional<List<String>>> oauthAllowedScopes() {
        return Codegen.optional(this.oauthAllowedScopes);
    }
    /**
     * The OAuth 2.0 authorization endpoint for the Git repository.
     * 
     */
    @Export(name="oauthAuthorizationEndpoint", refs={String.class}, tree="[0]")
    private Output<String> oauthAuthorizationEndpoint;

    /**
     * @return The OAuth 2.0 authorization endpoint for the Git repository.
     * 
     */
    public Output<String> oauthAuthorizationEndpoint() {
        return this.oauthAuthorizationEndpoint;
    }
    /**
     * The client ID for the OAuth 2.0 application.
     * 
     */
    @Export(name="oauthClientId", refs={String.class}, tree="[0]")
    private Output<String> oauthClientId;

    /**
     * @return The client ID for the OAuth 2.0 application.
     * 
     */
    public Output<String> oauthClientId() {
        return this.oauthClientId;
    }
    /**
     * The client secret for the OAuth 2.0 application. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
     * 
     */
    @Export(name="oauthClientSecret", refs={String.class}, tree="[0]")
    private Output<String> oauthClientSecret;

    /**
     * @return The client secret for the OAuth 2.0 application. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
     * 
     */
    public Output<String> oauthClientSecret() {
        return this.oauthClientSecret;
    }
    /**
     * Specifies the validity period (in seconds) for the OAuth 2.0 refresh token.
     * 
     */
    @Export(name="oauthRefreshTokenValidity", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> oauthRefreshTokenValidity;

    /**
     * @return Specifies the validity period (in seconds) for the OAuth 2.0 refresh token.
     * 
     */
    public Output<Optional<Integer>> oauthRefreshTokenValidity() {
        return Codegen.optional(this.oauthRefreshTokenValidity);
    }
    /**
     * The OAuth 2.0 token endpoint for the Git repository.
     * 
     */
    @Export(name="oauthTokenEndpoint", refs={String.class}, tree="[0]")
    private Output<String> oauthTokenEndpoint;

    /**
     * @return The OAuth 2.0 token endpoint for the Git repository.
     * 
     */
    public Output<String> oauthTokenEndpoint() {
        return this.oauthTokenEndpoint;
    }
    /**
     * Specifies the username to authenticate with the Git repository using OAuth 2.0.
     * 
     */
    @Export(name="oauthUsername", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> oauthUsername;

    /**
     * @return Specifies the username to authenticate with the Git repository using OAuth 2.0.
     * 
     */
    public Output<Optional<String>> oauthUsername() {
        return Codegen.optional(this.oauthUsername);
    }
    /**
     * Outputs the result of `SHOW API INTEGRATIONS` for the given integration.
     * 
     */
    @Export(name="showOutputs", refs={List.class,ApiIntegrationGitRepositoryOauth2ShowOutput.class}, tree="[0,1]")
    private Output<List<ApiIntegrationGitRepositoryOauth2ShowOutput>> showOutputs;

    /**
     * @return Outputs the result of `SHOW API INTEGRATIONS` for the given integration.
     * 
     */
    public Output<List<ApiIntegrationGitRepositoryOauth2ShowOutput>> showOutputs() {
        return this.showOutputs;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ApiIntegrationGitRepositoryOauth2(java.lang.String name) {
        this(name, ApiIntegrationGitRepositoryOauth2Args.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ApiIntegrationGitRepositoryOauth2(java.lang.String name, ApiIntegrationGitRepositoryOauth2Args args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ApiIntegrationGitRepositoryOauth2(java.lang.String name, ApiIntegrationGitRepositoryOauth2Args args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("snowflake:index/apiIntegrationGitRepositoryOauth2:ApiIntegrationGitRepositoryOauth2", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ApiIntegrationGitRepositoryOauth2(java.lang.String name, Output<java.lang.String> id, @Nullable ApiIntegrationGitRepositoryOauth2State state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("snowflake:index/apiIntegrationGitRepositoryOauth2:ApiIntegrationGitRepositoryOauth2", name, state, makeResourceOptions(options, id), false);
    }

    private static ApiIntegrationGitRepositoryOauth2Args makeArgs(ApiIntegrationGitRepositoryOauth2Args args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ApiIntegrationGitRepositoryOauth2Args.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "oauthClientSecret"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ApiIntegrationGitRepositoryOauth2 get(java.lang.String name, Output<java.lang.String> id, @Nullable ApiIntegrationGitRepositoryOauth2State state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ApiIntegrationGitRepositoryOauth2(name, id, state, options);
    }
}
