// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.snowflake.FileFormatAvroArgs;
import com.pulumi.snowflake.Utilities;
import com.pulumi.snowflake.inputs.FileFormatAvroState;
import com.pulumi.snowflake.outputs.FileFormatAvroDescribeOutput;
import com.pulumi.snowflake.outputs.FileFormatAvroShowOutput;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * &gt; **Caution: Preview Feature** This feature is considered a preview feature in the provider, regardless of the state of the resource in Snowflake. We do not guarantee its stability. It will be reworked and marked as a stable feature in future releases. Breaking changes are expected, even without bumping the major version. To use this feature, add the relevant feature name to `previewFeaturesEnabled` field in the provider configuration. Please always refer to the Getting Help section in our Github repo to best determine how to get help for your questions.
 * 
 * &gt; **Note** A file format cannot be dropped successfully if it has dependent external tables. Before dropping the resource, first drop the dependent external tables manually.
 * 
 * &gt; **Note** Snowflake returns the same `DESCRIBE FILE FORMAT` output for `nullIf` set to an empty list and for `nullIf` set to a list with a single empty string. Because of that, the provider cannot detect an external change between these two values, and `describe_output.null_if` is empty in both cases.
 * 
 * Resource used to manage AVRO file formats. For more information, check [file format documentation](https://docs.snowflake.com/en/sql-reference/sql/create-file-format).
 * 
 * ## Example Usage
 * 
 * &gt; **Note** Instead of using fully_qualified_name, you can reference objects managed outside Terraform by constructing a correct ID, consult identifiers guide.
 * &lt;!-- TODO(SNOW-1634854): include an example showing both methods--&gt;
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.snowflake.FileFormatAvro;
 * import com.pulumi.snowflake.FileFormatAvroArgs;
 * import java.util.ArrayList;
 * import java.util.Arrays;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         //# Minimal
 *         var basic = new FileFormatAvro("basic", FileFormatAvroArgs.builder()
 *             .database("database_name")
 *             .schema("schema_name")
 *             .name("file_format_name")
 *             .build());
 * 
 *         //# Complete (with every optional set)
 *         var complete = new FileFormatAvro("complete", FileFormatAvroArgs.builder()
 *             .database("database_name")
 *             .schema("schema_name")
 *             .name("file_format_name")
 *             .compression("GZIP")
 *             .trimSpace("true")
 *             .replaceInvalidCharacters("false")
 *             .nullIfs(            
 *                 "NULL",
 *                 "")
 *             .comment("My AVRO file format")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * &gt; **Note** If a field has a default value, it is shown next to the type in the schema.
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import snowflake:index/fileFormatAvro:FileFormatAvro example &#39;&#34;&lt;database_name&gt;&#34;.&#34;&lt;schema_name&gt;&#34;.&#34;&lt;file_format_name&gt;&#34;&#39;
 * ```
 * 
 */
@ResourceType(type="snowflake:index/fileFormatAvro:FileFormatAvro")
public class FileFormatAvro extends com.pulumi.resources.CustomResource {
    /**
     * Specifies a comment for the file format.
     * 
     */
    @Export(name="comment", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> comment;

    /**
     * @return Specifies a comment for the file format.
     * 
     */
    public Output<Optional<String>> comment() {
        return Codegen.optional(this.comment);
    }
    /**
     * Specifies the compression format. Valid values: `AUTO` | `GZIP` | `BROTLI` | `ZSTD` | `DEFLATE` | `RAW_DEFLATE` | `NONE`.
     * 
     */
    @Export(name="compression", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> compression;

    /**
     * @return Specifies the compression format. Valid values: `AUTO` | `GZIP` | `BROTLI` | `ZSTD` | `DEFLATE` | `RAW_DEFLATE` | `NONE`.
     * 
     */
    public Output<Optional<String>> compression() {
        return Codegen.optional(this.compression);
    }
    /**
     * The database in which to create the file format. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    @Export(name="database", refs={String.class}, tree="[0]")
    private Output<String> database;

    /**
     * @return The database in which to create the file format. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    public Output<String> database() {
        return this.database;
    }
    /**
     * Outputs the result of `DESCRIBE FILE FORMAT` for this file format.
     * 
     */
    @Export(name="describeOutputs", refs={List.class,FileFormatAvroDescribeOutput.class}, tree="[0,1]")
    private Output<List<FileFormatAvroDescribeOutput>> describeOutputs;

    /**
     * @return Outputs the result of `DESCRIBE FILE FORMAT` for this file format.
     * 
     */
    public Output<List<FileFormatAvroDescribeOutput>> describeOutputs() {
        return this.describeOutputs;
    }
    /**
     * Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
     * 
     */
    @Export(name="fullyQualifiedName", refs={String.class}, tree="[0]")
    private Output<String> fullyQualifiedName;

    /**
     * @return Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
     * 
     */
    public Output<String> fullyQualifiedName() {
        return this.fullyQualifiedName;
    }
    /**
     * Specifies the identifier for the file format; must be unique for the database and schema in which the file format is created. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Specifies the identifier for the file format; must be unique for the database and schema in which the file format is created. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * String used to convert to and from SQL NULL.
     * 
     */
    @Export(name="nullIfs", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> nullIfs;

    /**
     * @return String used to convert to and from SQL NULL.
     * 
     */
    public Output<Optional<List<String>>> nullIfs() {
        return Codegen.optional(this.nullIfs);
    }
    /**
     * (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Boolean that specifies whether to replace invalid UTF-8 characters with the Unicode replacement character. Available options are: &#34;true&#34; or &#34;false&#34;. When the value is not set in the configuration the provider will put &#34;default&#34; there which means to use the Snowflake default for this value.
     * 
     */
    @Export(name="replaceInvalidCharacters", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> replaceInvalidCharacters;

    /**
     * @return (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Boolean that specifies whether to replace invalid UTF-8 characters with the Unicode replacement character. Available options are: &#34;true&#34; or &#34;false&#34;. When the value is not set in the configuration the provider will put &#34;default&#34; there which means to use the Snowflake default for this value.
     * 
     */
    public Output<Optional<String>> replaceInvalidCharacters() {
        return Codegen.optional(this.replaceInvalidCharacters);
    }
    /**
     * The schema in which to create the file format. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    @Export(name="schema", refs={String.class}, tree="[0]")
    private Output<String> schema;

    /**
     * @return The schema in which to create the file format. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    public Output<String> schema() {
        return this.schema;
    }
    /**
     * Outputs the result of `SHOW FILE FORMATS` for this file format.
     * 
     */
    @Export(name="showOutputs", refs={List.class,FileFormatAvroShowOutput.class}, tree="[0,1]")
    private Output<List<FileFormatAvroShowOutput>> showOutputs;

    /**
     * @return Outputs the result of `SHOW FILE FORMATS` for this file format.
     * 
     */
    public Output<List<FileFormatAvroShowOutput>> showOutputs() {
        return this.showOutputs;
    }
    /**
     * (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Boolean that specifies whether to remove white space from fields. Available options are: &#34;true&#34; or &#34;false&#34;. When the value is not set in the configuration the provider will put &#34;default&#34; there which means to use the Snowflake default for this value.
     * 
     */
    @Export(name="trimSpace", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> trimSpace;

    /**
     * @return (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Boolean that specifies whether to remove white space from fields. Available options are: &#34;true&#34; or &#34;false&#34;. When the value is not set in the configuration the provider will put &#34;default&#34; there which means to use the Snowflake default for this value.
     * 
     */
    public Output<Optional<String>> trimSpace() {
        return Codegen.optional(this.trimSpace);
    }
    /**
     * Specifies the type of the file format. This field is used to detect when the file format type was changed outside of Terraform and to recreate the resource when that happens.
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return Specifies the type of the file format. This field is used to detect when the file format type was changed outside of Terraform and to recreate the resource when that happens.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public FileFormatAvro(java.lang.String name) {
        this(name, FileFormatAvroArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public FileFormatAvro(java.lang.String name, FileFormatAvroArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public FileFormatAvro(java.lang.String name, FileFormatAvroArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("snowflake:index/fileFormatAvro:FileFormatAvro", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private FileFormatAvro(java.lang.String name, Output<java.lang.String> id, @Nullable FileFormatAvroState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("snowflake:index/fileFormatAvro:FileFormatAvro", name, state, makeResourceOptions(options, id), false);
    }

    private static FileFormatAvroArgs makeArgs(FileFormatAvroArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? FileFormatAvroArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static FileFormatAvro get(java.lang.String name, Output<java.lang.String> id, @Nullable FileFormatAvroState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new FileFormatAvro(name, id, state, options);
    }
}
