// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.snowflake.SecondaryConnectionArgs;
import com.pulumi.snowflake.Utilities;
import com.pulumi.snowflake.inputs.SecondaryConnectionState;
import com.pulumi.snowflake.outputs.SecondaryConnectionShowOutput;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Resource used to manage secondary (replicated) connections. To manage primary connection check resource snowflake_primary_connection. For more information, check [connection documentation](https://docs.snowflake.com/en/sql-reference/sql/create-connection.html).
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.snowflake.SecondaryConnection;
 * import com.pulumi.snowflake.SecondaryConnectionArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         //# Minimal
 *         var basic = new SecondaryConnection("basic", SecondaryConnectionArgs.builder()
 *             .name("connection_name")
 *             .asReplicaOf("\"<organization_name>\".\"<account_name>\".\"<connection_name>\"")
 *             .build());
 * 
 *         //# Complete (with every optional set)
 *         var complete = new SecondaryConnection("complete", SecondaryConnectionArgs.builder()
 *             .name("connection_name")
 *             .asReplicaOf("\"<organization_name>\".\"<account_name>\".\"<connection_name>\"")
 *             .comment("my complete secondary connection")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * &gt; **Note** Instead of using fully_qualified_name, you can reference objects managed outside Terraform by constructing a correct ID, consult identifiers guide.
 * 
 * &gt; **Note** When creating a `snowflake.SecondaryConnection` and `snowflake.PrimaryConnection` in one `pulumi up` run, the `snowflake.SecondaryConnection` may return errors, because Snowflake needs some time to register the primary connection before you can create secondary connections based on it. The provider is handling it internally with a retry mechanism, but the time to register may differ and be longer than retry&#39;s maximum wait time. Generally, it is recommended to create the `snowflake.PrimaryConnection` first, then create the `snowflake.SecondaryConnection` in a second `pulumi up` run. If you tried to create both in one run, and it failed, just re-run the `pulumi up`. The time between both runs should be enough for Snowflake to register the primary connection.
 * 
 * &gt; **Note** To promote `snowflake.SecondaryConnection` to `snowflake.PrimaryConnection`, resources need to be migrated manually. For guidance on removing and importing resources into the state check resource migration. Remove the resource from the state with terraform state rm, then promote it manually using:
 *     ```    ALTER CONNECTION &lt;name&gt; PRIMARY;
 *     ```
 * and then import it as the `snowflake.PrimaryConnection`.
 * &lt;!-- TODO(SNOW-1634854): include an example showing both methods--&gt;
 * 
 * &gt; **Note** If a field has a default value, it is shown next to the type in the schema.
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import snowflake:index/secondaryConnection:SecondaryConnection example &#39;&#34;&lt;secondary_connection_name&gt;&#34;&#39;
 * ```
 * 
 */
@ResourceType(type="snowflake:index/secondaryConnection:SecondaryConnection")
public class SecondaryConnection extends com.pulumi.resources.CustomResource {
    /**
     * Specifies the identifier for a primary connection from which to create a replica (i.e. a secondary connection). For more information about this resource, see docs.
     * 
     */
    @Export(name="asReplicaOf", refs={String.class}, tree="[0]")
    private Output<String> asReplicaOf;

    /**
     * @return Specifies the identifier for a primary connection from which to create a replica (i.e. a secondary connection). For more information about this resource, see docs.
     * 
     */
    public Output<String> asReplicaOf() {
        return this.asReplicaOf;
    }
    /**
     * Specifies a comment for the secondary connection.
     * 
     */
    @Export(name="comment", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> comment;

    /**
     * @return Specifies a comment for the secondary connection.
     * 
     */
    public Output<Optional<String>> comment() {
        return Codegen.optional(this.comment);
    }
    /**
     * Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
     * 
     */
    @Export(name="fullyQualifiedName", refs={String.class}, tree="[0]")
    private Output<String> fullyQualifiedName;

    /**
     * @return Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
     * 
     */
    public Output<String> fullyQualifiedName() {
        return this.fullyQualifiedName;
    }
    /**
     * Indicates if the connection primary status has been changed. If change is detected, resource will be recreated.
     * 
     */
    @Export(name="isPrimary", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> isPrimary;

    /**
     * @return Indicates if the connection primary status has been changed. If change is detected, resource will be recreated.
     * 
     */
    public Output<Boolean> isPrimary() {
        return this.isPrimary;
    }
    /**
     * String that specifies the identifier (i.e. name) for the connection. Must start with an alphabetic character and may only contain letters, decimal digits (0-9), and underscores (*). For a secondary connection, the name must match the name of its primary connection. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return String that specifies the identifier (i.e. name) for the connection. Must start with an alphabetic character and may only contain letters, decimal digits (0-9), and underscores (*). For a secondary connection, the name must match the name of its primary connection. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Outputs the result of `SHOW CONNECTIONS` for the given connection.
     * 
     */
    @Export(name="showOutputs", refs={List.class,SecondaryConnectionShowOutput.class}, tree="[0,1]")
    private Output<List<SecondaryConnectionShowOutput>> showOutputs;

    /**
     * @return Outputs the result of `SHOW CONNECTIONS` for the given connection.
     * 
     */
    public Output<List<SecondaryConnectionShowOutput>> showOutputs() {
        return this.showOutputs;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SecondaryConnection(java.lang.String name) {
        this(name, SecondaryConnectionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SecondaryConnection(java.lang.String name, SecondaryConnectionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SecondaryConnection(java.lang.String name, SecondaryConnectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("snowflake:index/secondaryConnection:SecondaryConnection", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SecondaryConnection(java.lang.String name, Output<java.lang.String> id, @Nullable SecondaryConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("snowflake:index/secondaryConnection:SecondaryConnection", name, state, makeResourceOptions(options, id), false);
    }

    private static SecondaryConnectionArgs makeArgs(SecondaryConnectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SecondaryConnectionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SecondaryConnection get(java.lang.String name, Output<java.lang.String> id, @Nullable SecondaryConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SecondaryConnection(name, id, state, options);
    }
}
