// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ExternalVolumeDescribeOutputStorageLocationGcsStorageLocation {
    private @Nullable String encryptionKmsKeyId;
    private @Nullable String storageGcpServiceAccount;

    private ExternalVolumeDescribeOutputStorageLocationGcsStorageLocation() {}
    public Optional<String> encryptionKmsKeyId() {
        return Optional.ofNullable(this.encryptionKmsKeyId);
    }
    public Optional<String> storageGcpServiceAccount() {
        return Optional.ofNullable(this.storageGcpServiceAccount);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ExternalVolumeDescribeOutputStorageLocationGcsStorageLocation defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String encryptionKmsKeyId;
        private @Nullable String storageGcpServiceAccount;
        public Builder() {}
        public Builder(ExternalVolumeDescribeOutputStorageLocationGcsStorageLocation defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.encryptionKmsKeyId = defaults.encryptionKmsKeyId;
    	      this.storageGcpServiceAccount = defaults.storageGcpServiceAccount;
        }

        @CustomType.Setter
        public Builder encryptionKmsKeyId(@Nullable String encryptionKmsKeyId) {

            this.encryptionKmsKeyId = encryptionKmsKeyId;
            return this;
        }
        @CustomType.Setter
        public Builder storageGcpServiceAccount(@Nullable String storageGcpServiceAccount) {

            this.storageGcpServiceAccount = storageGcpServiceAccount;
            return this;
        }
        public ExternalVolumeDescribeOutputStorageLocationGcsStorageLocation build() {
            final var _resultValue = new ExternalVolumeDescribeOutputStorageLocationGcsStorageLocation();
            _resultValue.encryptionKmsKeyId = encryptionKmsKeyId;
            _resultValue.storageGcpServiceAccount = storageGcpServiceAccount;
            return _resultValue;
        }
    }
}
