// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.snowflake.outputs.GetStagesStage;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetStagesResult {
    /**
     * @return The database from which to return the schemas from.
     * 
     */
    private String database;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The schema from which to return the stages from.
     * 
     */
    private String schema;
    /**
     * @return The stages in the schema
     * 
     */
    private List<GetStagesStage> stages;

    private GetStagesResult() {}
    /**
     * @return The database from which to return the schemas from.
     * 
     */
    public String database() {
        return this.database;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The schema from which to return the stages from.
     * 
     */
    public String schema() {
        return this.schema;
    }
    /**
     * @return The stages in the schema
     * 
     */
    public List<GetStagesStage> stages() {
        return this.stages;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetStagesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String database;
        private String id;
        private String schema;
        private List<GetStagesStage> stages;
        public Builder() {}
        public Builder(GetStagesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.database = defaults.database;
    	      this.id = defaults.id;
    	      this.schema = defaults.schema;
    	      this.stages = defaults.stages;
        }

        @CustomType.Setter
        public Builder database(String database) {
            if (database == null) {
              throw new MissingRequiredPropertyException("GetStagesResult", "database");
            }
            this.database = database;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetStagesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder schema(String schema) {
            if (schema == null) {
              throw new MissingRequiredPropertyException("GetStagesResult", "schema");
            }
            this.schema = schema;
            return this;
        }
        @CustomType.Setter
        public Builder stages(List<GetStagesStage> stages) {
            if (stages == null) {
              throw new MissingRequiredPropertyException("GetStagesResult", "stages");
            }
            this.stages = stages;
            return this;
        }
        public Builder stages(GetStagesStage... stages) {
            return stages(List.of(stages));
        }
        public GetStagesResult build() {
            final var _resultValue = new GetStagesResult();
            _resultValue.database = database;
            _resultValue.id = id;
            _resultValue.schema = schema;
            _resultValue.stages = stages;
            return _resultValue;
        }
    }
}
