// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ProcedureJavascriptArgument {
    /**
     * @return The argument type.
     * 
     */
    private String argDataType;
    private @Nullable String argDefaultValue;
    /**
     * @return The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
     * 
     */
    private String argName;

    private ProcedureJavascriptArgument() {}
    /**
     * @return The argument type.
     * 
     */
    public String argDataType() {
        return this.argDataType;
    }
    public Optional<String> argDefaultValue() {
        return Optional.ofNullable(this.argDefaultValue);
    }
    /**
     * @return The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
     * 
     */
    public String argName() {
        return this.argName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ProcedureJavascriptArgument defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String argDataType;
        private @Nullable String argDefaultValue;
        private String argName;
        public Builder() {}
        public Builder(ProcedureJavascriptArgument defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.argDataType = defaults.argDataType;
    	      this.argDefaultValue = defaults.argDefaultValue;
    	      this.argName = defaults.argName;
        }

        @CustomType.Setter
        public Builder argDataType(String argDataType) {
            if (argDataType == null) {
              throw new MissingRequiredPropertyException("ProcedureJavascriptArgument", "argDataType");
            }
            this.argDataType = argDataType;
            return this;
        }
        @CustomType.Setter
        public Builder argDefaultValue(@Nullable String argDefaultValue) {

            this.argDefaultValue = argDefaultValue;
            return this;
        }
        @CustomType.Setter
        public Builder argName(String argName) {
            if (argName == null) {
              throw new MissingRequiredPropertyException("ProcedureJavascriptArgument", "argName");
            }
            this.argName = argName;
            return this;
        }
        public ProcedureJavascriptArgument build() {
            final var _resultValue = new ProcedureJavascriptArgument();
            _resultValue.argDataType = argDataType;
            _resultValue.argDefaultValue = argDefaultValue;
            _resultValue.argName = argName;
            return _resultValue;
        }
    }
}
