// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Snowflake.Outputs
{

    [OutputType]
    public sealed class GetStreamlitsStreamlitShowOutputResult
    {
        public readonly string Comment;
        public readonly string CreatedOn;
        public readonly string DatabaseName;
        public readonly string Name;
        public readonly string Owner;
        public readonly string OwnerRoleType;
        public readonly string QueryWarehouse;
        public readonly string SchemaName;
        public readonly string Title;
        public readonly string UrlId;

        [OutputConstructor]
        private GetStreamlitsStreamlitShowOutputResult(
            string comment,

            string createdOn,

            string databaseName,

            string name,

            string owner,

            string ownerRoleType,

            string queryWarehouse,

            string schemaName,

            string title,

            string urlId)
        {
            Comment = comment;
            CreatedOn = createdOn;
            DatabaseName = databaseName;
            Name = name;
            Owner = owner;
            OwnerRoleType = ownerRoleType;
            QueryWarehouse = queryWarehouse;
            SchemaName = schemaName;
            Title = title;
            UrlId = urlId;
        }
    }
}
