// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Snowflake.Outputs
{

    [OutputType]
    public sealed class MaskingPolicySignature
    {
        public readonly ImmutableArray<Outputs.MaskingPolicySignatureColumn> Columns;

        [OutputConstructor]
        private MaskingPolicySignature(ImmutableArray<Outputs.MaskingPolicySignatureColumn> columns)
        {
            Columns = columns;
        }
    }
}
