// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Snowflake.Outputs
{

    [OutputType]
    public sealed class OpenflowDeploymentSnowflakeManagedParameter
    {
        public readonly ImmutableArray<Outputs.OpenflowDeploymentSnowflakeManagedParameterEventTable> EventTables;

        [OutputConstructor]
        private OpenflowDeploymentSnowflakeManagedParameter(ImmutableArray<Outputs.OpenflowDeploymentSnowflakeManagedParameterEventTable> eventTables)
        {
            EventTables = eventTables;
        }
    }
}
