// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.snowflake.inputs.ApiIntegrationGitRepositoryTokenDescribeOutputArgs;
import com.pulumi.snowflake.inputs.ApiIntegrationGitRepositoryTokenShowOutputArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ApiIntegrationGitRepositoryTokenState extends com.pulumi.resources.ResourceArgs {

    public static final ApiIntegrationGitRepositoryTokenState Empty = new ApiIntegrationGitRepositoryTokenState();

    /**
     * When set to true, all authentication secrets are allowed to be used when authenticating to the git repository. Conflicts with `noAllowedAuthenticationSecrets` and `allowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
     * 
     */
    @Import(name="allAllowedAuthenticationSecrets")
    private @Nullable Output<Boolean> allAllowedAuthenticationSecrets;

    /**
     * @return When set to true, all authentication secrets are allowed to be used when authenticating to the git repository. Conflicts with `noAllowedAuthenticationSecrets` and `allowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
     * 
     */
    public Optional<Output<Boolean>> allAllowedAuthenticationSecrets() {
        return Optional.ofNullable(this.allAllowedAuthenticationSecrets);
    }

    /**
     * A list of fully-qualified secret identifiers (database.schema.secret) allowed to be used when authenticating to the git repository. Conflicts with `allAllowedAuthenticationSecrets` and `noAllowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
     * 
     */
    @Import(name="allowedAuthenticationSecrets")
    private @Nullable Output<List<String>> allowedAuthenticationSecrets;

    /**
     * @return A list of fully-qualified secret identifiers (database.schema.secret) allowed to be used when authenticating to the git repository. Conflicts with `allAllowedAuthenticationSecrets` and `noAllowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
     * 
     */
    public Optional<Output<List<String>>> allowedAuthenticationSecrets() {
        return Optional.ofNullable(this.allowedAuthenticationSecrets);
    }

    /**
     * Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
     * 
     */
    @Import(name="apiAllowedPrefixes")
    private @Nullable Output<List<String>> apiAllowedPrefixes;

    /**
     * @return Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
     * 
     */
    public Optional<Output<List<String>>> apiAllowedPrefixes() {
        return Optional.ofNullable(this.apiAllowedPrefixes);
    }

    /**
     * Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
     * 
     */
    @Import(name="apiBlockedPrefixes")
    private @Nullable Output<List<String>> apiBlockedPrefixes;

    /**
     * @return Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
     * 
     */
    public Optional<Output<List<String>>> apiBlockedPrefixes() {
        return Optional.ofNullable(this.apiBlockedPrefixes);
    }

    /**
     * Specifies a comment for the integration.
     * 
     */
    @Import(name="comment")
    private @Nullable Output<String> comment;

    /**
     * @return Specifies a comment for the integration.
     * 
     */
    public Optional<Output<String>> comment() {
        return Optional.ofNullable(this.comment);
    }

    /**
     * Outputs the result of `DESCRIBE API INTEGRATION` for the given integration.
     * 
     */
    @Import(name="describeOutputs")
    private @Nullable Output<List<ApiIntegrationGitRepositoryTokenDescribeOutputArgs>> describeOutputs;

    /**
     * @return Outputs the result of `DESCRIBE API INTEGRATION` for the given integration.
     * 
     */
    public Optional<Output<List<ApiIntegrationGitRepositoryTokenDescribeOutputArgs>>> describeOutputs() {
        return Optional.ofNullable(this.describeOutputs);
    }

    /**
     * Specifies whether this API integration is enabled or disabled.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Specifies whether this API integration is enabled or disabled.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
     * 
     */
    @Import(name="fullyQualifiedName")
    private @Nullable Output<String> fullyQualifiedName;

    /**
     * @return Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
     * 
     */
    public Optional<Output<String>> fullyQualifiedName() {
        return Optional.ofNullable(this.fullyQualifiedName);
    }

    /**
     * Specifies the identifier (i.e. name) for the integration. This value must be unique in your account. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Specifies the identifier (i.e. name) for the integration. This value must be unique in your account. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * When set to true, no authentication secrets are allowed to be used when authenticating to the git repository. Conflicts with `allAllowedAuthenticationSecrets` and `allowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
     * 
     */
    @Import(name="noAllowedAuthenticationSecrets")
    private @Nullable Output<Boolean> noAllowedAuthenticationSecrets;

    /**
     * @return When set to true, no authentication secrets are allowed to be used when authenticating to the git repository. Conflicts with `allAllowedAuthenticationSecrets` and `allowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
     * 
     */
    public Optional<Output<Boolean>> noAllowedAuthenticationSecrets() {
        return Optional.ofNullable(this.noAllowedAuthenticationSecrets);
    }

    /**
     * Outputs the result of `SHOW API INTEGRATIONS` for the given integration.
     * 
     */
    @Import(name="showOutputs")
    private @Nullable Output<List<ApiIntegrationGitRepositoryTokenShowOutputArgs>> showOutputs;

    /**
     * @return Outputs the result of `SHOW API INTEGRATIONS` for the given integration.
     * 
     */
    public Optional<Output<List<ApiIntegrationGitRepositoryTokenShowOutputArgs>>> showOutputs() {
        return Optional.ofNullable(this.showOutputs);
    }

    private ApiIntegrationGitRepositoryTokenState() {}

    private ApiIntegrationGitRepositoryTokenState(ApiIntegrationGitRepositoryTokenState $) {
        this.allAllowedAuthenticationSecrets = $.allAllowedAuthenticationSecrets;
        this.allowedAuthenticationSecrets = $.allowedAuthenticationSecrets;
        this.apiAllowedPrefixes = $.apiAllowedPrefixes;
        this.apiBlockedPrefixes = $.apiBlockedPrefixes;
        this.comment = $.comment;
        this.describeOutputs = $.describeOutputs;
        this.enabled = $.enabled;
        this.fullyQualifiedName = $.fullyQualifiedName;
        this.name = $.name;
        this.noAllowedAuthenticationSecrets = $.noAllowedAuthenticationSecrets;
        this.showOutputs = $.showOutputs;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ApiIntegrationGitRepositoryTokenState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ApiIntegrationGitRepositoryTokenState $;

        public Builder() {
            $ = new ApiIntegrationGitRepositoryTokenState();
        }

        public Builder(ApiIntegrationGitRepositoryTokenState defaults) {
            $ = new ApiIntegrationGitRepositoryTokenState(Objects.requireNonNull(defaults));
        }

        /**
         * @param allAllowedAuthenticationSecrets When set to true, all authentication secrets are allowed to be used when authenticating to the git repository. Conflicts with `noAllowedAuthenticationSecrets` and `allowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
         * 
         * @return builder
         * 
         */
        public Builder allAllowedAuthenticationSecrets(@Nullable Output<Boolean> allAllowedAuthenticationSecrets) {
            $.allAllowedAuthenticationSecrets = allAllowedAuthenticationSecrets;
            return this;
        }

        /**
         * @param allAllowedAuthenticationSecrets When set to true, all authentication secrets are allowed to be used when authenticating to the git repository. Conflicts with `noAllowedAuthenticationSecrets` and `allowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
         * 
         * @return builder
         * 
         */
        public Builder allAllowedAuthenticationSecrets(Boolean allAllowedAuthenticationSecrets) {
            return allAllowedAuthenticationSecrets(Output.of(allAllowedAuthenticationSecrets));
        }

        /**
         * @param allowedAuthenticationSecrets A list of fully-qualified secret identifiers (database.schema.secret) allowed to be used when authenticating to the git repository. Conflicts with `allAllowedAuthenticationSecrets` and `noAllowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
         * 
         * @return builder
         * 
         */
        public Builder allowedAuthenticationSecrets(@Nullable Output<List<String>> allowedAuthenticationSecrets) {
            $.allowedAuthenticationSecrets = allowedAuthenticationSecrets;
            return this;
        }

        /**
         * @param allowedAuthenticationSecrets A list of fully-qualified secret identifiers (database.schema.secret) allowed to be used when authenticating to the git repository. Conflicts with `allAllowedAuthenticationSecrets` and `noAllowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
         * 
         * @return builder
         * 
         */
        public Builder allowedAuthenticationSecrets(List<String> allowedAuthenticationSecrets) {
            return allowedAuthenticationSecrets(Output.of(allowedAuthenticationSecrets));
        }

        /**
         * @param allowedAuthenticationSecrets A list of fully-qualified secret identifiers (database.schema.secret) allowed to be used when authenticating to the git repository. Conflicts with `allAllowedAuthenticationSecrets` and `noAllowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
         * 
         * @return builder
         * 
         */
        public Builder allowedAuthenticationSecrets(String... allowedAuthenticationSecrets) {
            return allowedAuthenticationSecrets(List.of(allowedAuthenticationSecrets));
        }

        /**
         * @param apiAllowedPrefixes Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
         * 
         * @return builder
         * 
         */
        public Builder apiAllowedPrefixes(@Nullable Output<List<String>> apiAllowedPrefixes) {
            $.apiAllowedPrefixes = apiAllowedPrefixes;
            return this;
        }

        /**
         * @param apiAllowedPrefixes Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
         * 
         * @return builder
         * 
         */
        public Builder apiAllowedPrefixes(List<String> apiAllowedPrefixes) {
            return apiAllowedPrefixes(Output.of(apiAllowedPrefixes));
        }

        /**
         * @param apiAllowedPrefixes Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service and remote service endpoints and resources.
         * 
         * @return builder
         * 
         */
        public Builder apiAllowedPrefixes(String... apiAllowedPrefixes) {
            return apiAllowedPrefixes(List.of(apiAllowedPrefixes));
        }

        /**
         * @param apiBlockedPrefixes Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
         * 
         * @return builder
         * 
         */
        public Builder apiBlockedPrefixes(@Nullable Output<List<String>> apiBlockedPrefixes) {
            $.apiBlockedPrefixes = apiBlockedPrefixes;
            return this;
        }

        /**
         * @param apiBlockedPrefixes Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
         * 
         * @return builder
         * 
         */
        public Builder apiBlockedPrefixes(List<String> apiBlockedPrefixes) {
            return apiBlockedPrefixes(Output.of(apiBlockedPrefixes));
        }

        /**
         * @param apiBlockedPrefixes Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
         * 
         * @return builder
         * 
         */
        public Builder apiBlockedPrefixes(String... apiBlockedPrefixes) {
            return apiBlockedPrefixes(List.of(apiBlockedPrefixes));
        }

        /**
         * @param comment Specifies a comment for the integration.
         * 
         * @return builder
         * 
         */
        public Builder comment(@Nullable Output<String> comment) {
            $.comment = comment;
            return this;
        }

        /**
         * @param comment Specifies a comment for the integration.
         * 
         * @return builder
         * 
         */
        public Builder comment(String comment) {
            return comment(Output.of(comment));
        }

        /**
         * @param describeOutputs Outputs the result of `DESCRIBE API INTEGRATION` for the given integration.
         * 
         * @return builder
         * 
         */
        public Builder describeOutputs(@Nullable Output<List<ApiIntegrationGitRepositoryTokenDescribeOutputArgs>> describeOutputs) {
            $.describeOutputs = describeOutputs;
            return this;
        }

        /**
         * @param describeOutputs Outputs the result of `DESCRIBE API INTEGRATION` for the given integration.
         * 
         * @return builder
         * 
         */
        public Builder describeOutputs(List<ApiIntegrationGitRepositoryTokenDescribeOutputArgs> describeOutputs) {
            return describeOutputs(Output.of(describeOutputs));
        }

        /**
         * @param describeOutputs Outputs the result of `DESCRIBE API INTEGRATION` for the given integration.
         * 
         * @return builder
         * 
         */
        public Builder describeOutputs(ApiIntegrationGitRepositoryTokenDescribeOutputArgs... describeOutputs) {
            return describeOutputs(List.of(describeOutputs));
        }

        /**
         * @param enabled Specifies whether this API integration is enabled or disabled.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Specifies whether this API integration is enabled or disabled.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param fullyQualifiedName Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
         * 
         * @return builder
         * 
         */
        public Builder fullyQualifiedName(@Nullable Output<String> fullyQualifiedName) {
            $.fullyQualifiedName = fullyQualifiedName;
            return this;
        }

        /**
         * @param fullyQualifiedName Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
         * 
         * @return builder
         * 
         */
        public Builder fullyQualifiedName(String fullyQualifiedName) {
            return fullyQualifiedName(Output.of(fullyQualifiedName));
        }

        /**
         * @param name Specifies the identifier (i.e. name) for the integration. This value must be unique in your account. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Specifies the identifier (i.e. name) for the integration. This value must be unique in your account. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param noAllowedAuthenticationSecrets When set to true, no authentication secrets are allowed to be used when authenticating to the git repository. Conflicts with `allAllowedAuthenticationSecrets` and `allowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
         * 
         * @return builder
         * 
         */
        public Builder noAllowedAuthenticationSecrets(@Nullable Output<Boolean> noAllowedAuthenticationSecrets) {
            $.noAllowedAuthenticationSecrets = noAllowedAuthenticationSecrets;
            return this;
        }

        /**
         * @param noAllowedAuthenticationSecrets When set to true, no authentication secrets are allowed to be used when authenticating to the git repository. Conflicts with `allAllowedAuthenticationSecrets` and `allowedAuthenticationSecrets`. External changes for this field won&#39;t be detected. In case you want to apply external changes, you can re-create the resource manually using &#34;terraform taint&#34;.
         * 
         * @return builder
         * 
         */
        public Builder noAllowedAuthenticationSecrets(Boolean noAllowedAuthenticationSecrets) {
            return noAllowedAuthenticationSecrets(Output.of(noAllowedAuthenticationSecrets));
        }

        /**
         * @param showOutputs Outputs the result of `SHOW API INTEGRATIONS` for the given integration.
         * 
         * @return builder
         * 
         */
        public Builder showOutputs(@Nullable Output<List<ApiIntegrationGitRepositoryTokenShowOutputArgs>> showOutputs) {
            $.showOutputs = showOutputs;
            return this;
        }

        /**
         * @param showOutputs Outputs the result of `SHOW API INTEGRATIONS` for the given integration.
         * 
         * @return builder
         * 
         */
        public Builder showOutputs(List<ApiIntegrationGitRepositoryTokenShowOutputArgs> showOutputs) {
            return showOutputs(Output.of(showOutputs));
        }

        /**
         * @param showOutputs Outputs the result of `SHOW API INTEGRATIONS` for the given integration.
         * 
         * @return builder
         * 
         */
        public Builder showOutputs(ApiIntegrationGitRepositoryTokenShowOutputArgs... showOutputs) {
            return showOutputs(List.of(showOutputs));
        }

        public ApiIntegrationGitRepositoryTokenState build() {
            return $;
        }
    }

}
