// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class EmailNotificationIntegrationState extends com.pulumi.resources.ResourceArgs {

    public static final EmailNotificationIntegrationState Empty = new EmailNotificationIntegrationState();

    /**
     * List of email addresses that should receive notifications.
     * 
     */
    @Import(name="allowedRecipients")
    private @Nullable Output<List<String>> allowedRecipients;

    /**
     * @return List of email addresses that should receive notifications.
     * 
     */
    public Optional<Output<List<String>>> allowedRecipients() {
        return Optional.ofNullable(this.allowedRecipients);
    }

    /**
     * A comment for the email integration.
     * 
     */
    @Import(name="comment")
    private @Nullable Output<String> comment;

    /**
     * @return A comment for the email integration.
     * 
     */
    public Optional<Output<String>> comment() {
        return Optional.ofNullable(this.comment);
    }

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private EmailNotificationIntegrationState() {}

    private EmailNotificationIntegrationState(EmailNotificationIntegrationState $) {
        this.allowedRecipients = $.allowedRecipients;
        this.comment = $.comment;
        this.enabled = $.enabled;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EmailNotificationIntegrationState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EmailNotificationIntegrationState $;

        public Builder() {
            $ = new EmailNotificationIntegrationState();
        }

        public Builder(EmailNotificationIntegrationState defaults) {
            $ = new EmailNotificationIntegrationState(Objects.requireNonNull(defaults));
        }

        /**
         * @param allowedRecipients List of email addresses that should receive notifications.
         * 
         * @return builder
         * 
         */
        public Builder allowedRecipients(@Nullable Output<List<String>> allowedRecipients) {
            $.allowedRecipients = allowedRecipients;
            return this;
        }

        /**
         * @param allowedRecipients List of email addresses that should receive notifications.
         * 
         * @return builder
         * 
         */
        public Builder allowedRecipients(List<String> allowedRecipients) {
            return allowedRecipients(Output.of(allowedRecipients));
        }

        /**
         * @param allowedRecipients List of email addresses that should receive notifications.
         * 
         * @return builder
         * 
         */
        public Builder allowedRecipients(String... allowedRecipients) {
            return allowedRecipients(List.of(allowedRecipients));
        }

        /**
         * @param comment A comment for the email integration.
         * 
         * @return builder
         * 
         */
        public Builder comment(@Nullable Output<String> comment) {
            $.comment = comment;
            return this;
        }

        /**
         * @param comment A comment for the email integration.
         * 
         * @return builder
         * 
         */
        public Builder comment(String comment) {
            return comment(Output.of(comment));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public EmailNotificationIntegrationState build() {
            return $;
        }
    }

}
