// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs extends com.pulumi.resources.ResourceArgs {

    public static final IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs Empty = new IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs();

    @Import(name="currentSnapshotId")
    private @Nullable Output<Integer> currentSnapshotId;

    public Optional<Output<Integer>> currentSnapshotId() {
        return Optional.ofNullable(this.currentSnapshotId);
    }

    @Import(name="executionState")
    private @Nullable Output<String> executionState;

    public Optional<Output<String>> executionState() {
        return Optional.ofNullable(this.executionState);
    }

    @Import(name="lastSnapshotTime")
    private @Nullable Output<String> lastSnapshotTime;

    public Optional<Output<String>> lastSnapshotTime() {
        return Optional.ofNullable(this.lastSnapshotTime);
    }

    @Import(name="lastUpdatedTime")
    private @Nullable Output<String> lastUpdatedTime;

    public Optional<Output<String>> lastUpdatedTime() {
        return Optional.ofNullable(this.lastUpdatedTime);
    }

    @Import(name="pendingSnapshotCount")
    private @Nullable Output<Integer> pendingSnapshotCount;

    public Optional<Output<Integer>> pendingSnapshotCount() {
        return Optional.ofNullable(this.pendingSnapshotCount);
    }

    private IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs() {}

    private IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs(IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs $) {
        this.currentSnapshotId = $.currentSnapshotId;
        this.executionState = $.executionState;
        this.lastSnapshotTime = $.lastSnapshotTime;
        this.lastUpdatedTime = $.lastUpdatedTime;
        this.pendingSnapshotCount = $.pendingSnapshotCount;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs $;

        public Builder() {
            $ = new IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs();
        }

        public Builder(IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs defaults) {
            $ = new IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs(Objects.requireNonNull(defaults));
        }

        public Builder currentSnapshotId(@Nullable Output<Integer> currentSnapshotId) {
            $.currentSnapshotId = currentSnapshotId;
            return this;
        }

        public Builder currentSnapshotId(Integer currentSnapshotId) {
            return currentSnapshotId(Output.of(currentSnapshotId));
        }

        public Builder executionState(@Nullable Output<String> executionState) {
            $.executionState = executionState;
            return this;
        }

        public Builder executionState(String executionState) {
            return executionState(Output.of(executionState));
        }

        public Builder lastSnapshotTime(@Nullable Output<String> lastSnapshotTime) {
            $.lastSnapshotTime = lastSnapshotTime;
            return this;
        }

        public Builder lastSnapshotTime(String lastSnapshotTime) {
            return lastSnapshotTime(Output.of(lastSnapshotTime));
        }

        public Builder lastUpdatedTime(@Nullable Output<String> lastUpdatedTime) {
            $.lastUpdatedTime = lastUpdatedTime;
            return this;
        }

        public Builder lastUpdatedTime(String lastUpdatedTime) {
            return lastUpdatedTime(Output.of(lastUpdatedTime));
        }

        public Builder pendingSnapshotCount(@Nullable Output<Integer> pendingSnapshotCount) {
            $.pendingSnapshotCount = pendingSnapshotCount;
            return this;
        }

        public Builder pendingSnapshotCount(Integer pendingSnapshotCount) {
            return pendingSnapshotCount(Output.of(pendingSnapshotCount));
        }

        public IcebergTableFromAwsGlueShowOutputAutoRefreshStatusArgs build() {
            return $;
        }
    }

}
