// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.snowflake.inputs.NotebookDescribeOutputArgs;
import com.pulumi.snowflake.inputs.NotebookFromArgs;
import com.pulumi.snowflake.inputs.NotebookShowOutputArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NotebookState extends com.pulumi.resources.ResourceArgs {

    public static final NotebookState Empty = new NotebookState();

    /**
     * Specifies a comment for the notebook.
     * 
     */
    @Import(name="comment")
    private @Nullable Output<String> comment;

    /**
     * @return Specifies a comment for the notebook.
     * 
     */
    public Optional<Output<String>> comment() {
        return Optional.ofNullable(this.comment);
    }

    /**
     * The database in which to create the notebook. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    @Import(name="database")
    private @Nullable Output<String> database;

    /**
     * @return The database in which to create the notebook. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    public Optional<Output<String>> database() {
        return Optional.ofNullable(this.database);
    }

    /**
     * Outputs the result of `DESCRIBE NOTEBOOK` for the given notebook.
     * 
     */
    @Import(name="describeOutputs")
    private @Nullable Output<List<NotebookDescribeOutputArgs>> describeOutputs;

    /**
     * @return Outputs the result of `DESCRIBE NOTEBOOK` for the given notebook.
     * 
     */
    public Optional<Output<List<NotebookDescribeOutputArgs>>> describeOutputs() {
        return Optional.ofNullable(this.describeOutputs);
    }

    /**
     * Specifies the location in a stage of an .ipynb file from which the notebook should be created. MAIN_FILE parameter a user-specified identifier for the notebook file name must also be set alongside it.
     * 
     */
    @Import(name="froms")
    private @Nullable Output<List<NotebookFromArgs>> froms;

    /**
     * @return Specifies the location in a stage of an .ipynb file from which the notebook should be created. MAIN_FILE parameter a user-specified identifier for the notebook file name must also be set alongside it.
     * 
     */
    public Optional<Output<List<NotebookFromArgs>>> froms() {
        return Optional.ofNullable(this.froms);
    }

    /**
     * Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
     * 
     */
    @Import(name="fullyQualifiedName")
    private @Nullable Output<String> fullyQualifiedName;

    /**
     * @return Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
     * 
     */
    public Optional<Output<String>> fullyQualifiedName() {
        return Optional.ofNullable(this.fullyQualifiedName);
    }

    /**
     * Specifies the number of seconds of idle time before the notebook is shut down automatically.
     * 
     */
    @Import(name="idleAutoShutdownTimeSeconds")
    private @Nullable Output<Integer> idleAutoShutdownTimeSeconds;

    /**
     * @return Specifies the number of seconds of idle time before the notebook is shut down automatically.
     * 
     */
    public Optional<Output<Integer>> idleAutoShutdownTimeSeconds() {
        return Optional.ofNullable(this.idleAutoShutdownTimeSeconds);
    }

    /**
     * Specifies a user-specified identifier for the notebook file name.
     * 
     */
    @Import(name="mainFile")
    private @Nullable Output<String> mainFile;

    /**
     * @return Specifies a user-specified identifier for the notebook file name.
     * 
     */
    public Optional<Output<String>> mainFile() {
        return Optional.ofNullable(this.mainFile);
    }

    /**
     * Specifies the identifier for the notebook; must be unique for the schema in which the notebook is created. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Specifies the identifier for the notebook; must be unique for the schema in which the notebook is created. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Specifies the warehouse where SQL queries in the notebook are run.
     * 
     */
    @Import(name="queryWarehouse")
    private @Nullable Output<String> queryWarehouse;

    /**
     * @return Specifies the warehouse where SQL queries in the notebook are run.
     * 
     */
    public Optional<Output<String>> queryWarehouse() {
        return Optional.ofNullable(this.queryWarehouse);
    }

    /**
     * The schema in which to create the notebook. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    @Import(name="schema")
    private @Nullable Output<String> schema;

    /**
     * @return The schema in which to create the notebook. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
     * 
     */
    public Optional<Output<String>> schema() {
        return Optional.ofNullable(this.schema);
    }

    /**
     * Outputs the result of `SHOW NOTEBOOKS` for the given notebook
     * 
     */
    @Import(name="showOutputs")
    private @Nullable Output<List<NotebookShowOutputArgs>> showOutputs;

    /**
     * @return Outputs the result of `SHOW NOTEBOOKS` for the given notebook
     * 
     */
    public Optional<Output<List<NotebookShowOutputArgs>>> showOutputs() {
        return Optional.ofNullable(this.showOutputs);
    }

    /**
     * Specifies the warehouse that runs the notebook kernel and python code.
     * 
     */
    @Import(name="warehouse")
    private @Nullable Output<String> warehouse;

    /**
     * @return Specifies the warehouse that runs the notebook kernel and python code.
     * 
     */
    public Optional<Output<String>> warehouse() {
        return Optional.ofNullable(this.warehouse);
    }

    private NotebookState() {}

    private NotebookState(NotebookState $) {
        this.comment = $.comment;
        this.database = $.database;
        this.describeOutputs = $.describeOutputs;
        this.froms = $.froms;
        this.fullyQualifiedName = $.fullyQualifiedName;
        this.idleAutoShutdownTimeSeconds = $.idleAutoShutdownTimeSeconds;
        this.mainFile = $.mainFile;
        this.name = $.name;
        this.queryWarehouse = $.queryWarehouse;
        this.schema = $.schema;
        this.showOutputs = $.showOutputs;
        this.warehouse = $.warehouse;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotebookState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotebookState $;

        public Builder() {
            $ = new NotebookState();
        }

        public Builder(NotebookState defaults) {
            $ = new NotebookState(Objects.requireNonNull(defaults));
        }

        /**
         * @param comment Specifies a comment for the notebook.
         * 
         * @return builder
         * 
         */
        public Builder comment(@Nullable Output<String> comment) {
            $.comment = comment;
            return this;
        }

        /**
         * @param comment Specifies a comment for the notebook.
         * 
         * @return builder
         * 
         */
        public Builder comment(String comment) {
            return comment(Output.of(comment));
        }

        /**
         * @param database The database in which to create the notebook. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder database(@Nullable Output<String> database) {
            $.database = database;
            return this;
        }

        /**
         * @param database The database in which to create the notebook. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder database(String database) {
            return database(Output.of(database));
        }

        /**
         * @param describeOutputs Outputs the result of `DESCRIBE NOTEBOOK` for the given notebook.
         * 
         * @return builder
         * 
         */
        public Builder describeOutputs(@Nullable Output<List<NotebookDescribeOutputArgs>> describeOutputs) {
            $.describeOutputs = describeOutputs;
            return this;
        }

        /**
         * @param describeOutputs Outputs the result of `DESCRIBE NOTEBOOK` for the given notebook.
         * 
         * @return builder
         * 
         */
        public Builder describeOutputs(List<NotebookDescribeOutputArgs> describeOutputs) {
            return describeOutputs(Output.of(describeOutputs));
        }

        /**
         * @param describeOutputs Outputs the result of `DESCRIBE NOTEBOOK` for the given notebook.
         * 
         * @return builder
         * 
         */
        public Builder describeOutputs(NotebookDescribeOutputArgs... describeOutputs) {
            return describeOutputs(List.of(describeOutputs));
        }

        /**
         * @param froms Specifies the location in a stage of an .ipynb file from which the notebook should be created. MAIN_FILE parameter a user-specified identifier for the notebook file name must also be set alongside it.
         * 
         * @return builder
         * 
         */
        public Builder froms(@Nullable Output<List<NotebookFromArgs>> froms) {
            $.froms = froms;
            return this;
        }

        /**
         * @param froms Specifies the location in a stage of an .ipynb file from which the notebook should be created. MAIN_FILE parameter a user-specified identifier for the notebook file name must also be set alongside it.
         * 
         * @return builder
         * 
         */
        public Builder froms(List<NotebookFromArgs> froms) {
            return froms(Output.of(froms));
        }

        /**
         * @param froms Specifies the location in a stage of an .ipynb file from which the notebook should be created. MAIN_FILE parameter a user-specified identifier for the notebook file name must also be set alongside it.
         * 
         * @return builder
         * 
         */
        public Builder froms(NotebookFromArgs... froms) {
            return froms(List.of(froms));
        }

        /**
         * @param fullyQualifiedName Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
         * 
         * @return builder
         * 
         */
        public Builder fullyQualifiedName(@Nullable Output<String> fullyQualifiedName) {
            $.fullyQualifiedName = fullyQualifiedName;
            return this;
        }

        /**
         * @param fullyQualifiedName Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
         * 
         * @return builder
         * 
         */
        public Builder fullyQualifiedName(String fullyQualifiedName) {
            return fullyQualifiedName(Output.of(fullyQualifiedName));
        }

        /**
         * @param idleAutoShutdownTimeSeconds Specifies the number of seconds of idle time before the notebook is shut down automatically.
         * 
         * @return builder
         * 
         */
        public Builder idleAutoShutdownTimeSeconds(@Nullable Output<Integer> idleAutoShutdownTimeSeconds) {
            $.idleAutoShutdownTimeSeconds = idleAutoShutdownTimeSeconds;
            return this;
        }

        /**
         * @param idleAutoShutdownTimeSeconds Specifies the number of seconds of idle time before the notebook is shut down automatically.
         * 
         * @return builder
         * 
         */
        public Builder idleAutoShutdownTimeSeconds(Integer idleAutoShutdownTimeSeconds) {
            return idleAutoShutdownTimeSeconds(Output.of(idleAutoShutdownTimeSeconds));
        }

        /**
         * @param mainFile Specifies a user-specified identifier for the notebook file name.
         * 
         * @return builder
         * 
         */
        public Builder mainFile(@Nullable Output<String> mainFile) {
            $.mainFile = mainFile;
            return this;
        }

        /**
         * @param mainFile Specifies a user-specified identifier for the notebook file name.
         * 
         * @return builder
         * 
         */
        public Builder mainFile(String mainFile) {
            return mainFile(Output.of(mainFile));
        }

        /**
         * @param name Specifies the identifier for the notebook; must be unique for the schema in which the notebook is created. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Specifies the identifier for the notebook; must be unique for the schema in which the notebook is created. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param queryWarehouse Specifies the warehouse where SQL queries in the notebook are run.
         * 
         * @return builder
         * 
         */
        public Builder queryWarehouse(@Nullable Output<String> queryWarehouse) {
            $.queryWarehouse = queryWarehouse;
            return this;
        }

        /**
         * @param queryWarehouse Specifies the warehouse where SQL queries in the notebook are run.
         * 
         * @return builder
         * 
         */
        public Builder queryWarehouse(String queryWarehouse) {
            return queryWarehouse(Output.of(queryWarehouse));
        }

        /**
         * @param schema The schema in which to create the notebook. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder schema(@Nullable Output<String> schema) {
            $.schema = schema;
            return this;
        }

        /**
         * @param schema The schema in which to create the notebook. Due to technical limitations (read more here), avoid using the following characters: `|`, `.`, `&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder schema(String schema) {
            return schema(Output.of(schema));
        }

        /**
         * @param showOutputs Outputs the result of `SHOW NOTEBOOKS` for the given notebook
         * 
         * @return builder
         * 
         */
        public Builder showOutputs(@Nullable Output<List<NotebookShowOutputArgs>> showOutputs) {
            $.showOutputs = showOutputs;
            return this;
        }

        /**
         * @param showOutputs Outputs the result of `SHOW NOTEBOOKS` for the given notebook
         * 
         * @return builder
         * 
         */
        public Builder showOutputs(List<NotebookShowOutputArgs> showOutputs) {
            return showOutputs(Output.of(showOutputs));
        }

        /**
         * @param showOutputs Outputs the result of `SHOW NOTEBOOKS` for the given notebook
         * 
         * @return builder
         * 
         */
        public Builder showOutputs(NotebookShowOutputArgs... showOutputs) {
            return showOutputs(List.of(showOutputs));
        }

        /**
         * @param warehouse Specifies the warehouse that runs the notebook kernel and python code.
         * 
         * @return builder
         * 
         */
        public Builder warehouse(@Nullable Output<String> warehouse) {
            $.warehouse = warehouse;
            return this;
        }

        /**
         * @param warehouse Specifies the warehouse that runs the notebook kernel and python code.
         * 
         * @return builder
         * 
         */
        public Builder warehouse(String warehouse) {
            return warehouse(Output.of(warehouse));
        }

        public NotebookState build() {
            return $;
        }
    }

}
