// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.snowflake.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TaskTargetCompletionIntervalArgs extends com.pulumi.resources.ResourceArgs {

    public static final TaskTargetCompletionIntervalArgs Empty = new TaskTargetCompletionIntervalArgs();

    /**
     * Specifies the target completion interval in hours. (conflicts with `minutes` and `seconds`)
     * 
     */
    @Import(name="hours")
    private @Nullable Output<Integer> hours;

    /**
     * @return Specifies the target completion interval in hours. (conflicts with `minutes` and `seconds`)
     * 
     */
    public Optional<Output<Integer>> hours() {
        return Optional.ofNullable(this.hours);
    }

    /**
     * Specifies the target completion interval in minutes. (conflicts with `hours` and `seconds`)
     * 
     */
    @Import(name="minutes")
    private @Nullable Output<Integer> minutes;

    /**
     * @return Specifies the target completion interval in minutes. (conflicts with `hours` and `seconds`)
     * 
     */
    public Optional<Output<Integer>> minutes() {
        return Optional.ofNullable(this.minutes);
    }

    /**
     * Specifies the target completion interval in seconds. (conflicts with `hours` and `minutes`)
     * 
     */
    @Import(name="seconds")
    private @Nullable Output<Integer> seconds;

    /**
     * @return Specifies the target completion interval in seconds. (conflicts with `hours` and `minutes`)
     * 
     */
    public Optional<Output<Integer>> seconds() {
        return Optional.ofNullable(this.seconds);
    }

    private TaskTargetCompletionIntervalArgs() {}

    private TaskTargetCompletionIntervalArgs(TaskTargetCompletionIntervalArgs $) {
        this.hours = $.hours;
        this.minutes = $.minutes;
        this.seconds = $.seconds;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TaskTargetCompletionIntervalArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TaskTargetCompletionIntervalArgs $;

        public Builder() {
            $ = new TaskTargetCompletionIntervalArgs();
        }

        public Builder(TaskTargetCompletionIntervalArgs defaults) {
            $ = new TaskTargetCompletionIntervalArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param hours Specifies the target completion interval in hours. (conflicts with `minutes` and `seconds`)
         * 
         * @return builder
         * 
         */
        public Builder hours(@Nullable Output<Integer> hours) {
            $.hours = hours;
            return this;
        }

        /**
         * @param hours Specifies the target completion interval in hours. (conflicts with `minutes` and `seconds`)
         * 
         * @return builder
         * 
         */
        public Builder hours(Integer hours) {
            return hours(Output.of(hours));
        }

        /**
         * @param minutes Specifies the target completion interval in minutes. (conflicts with `hours` and `seconds`)
         * 
         * @return builder
         * 
         */
        public Builder minutes(@Nullable Output<Integer> minutes) {
            $.minutes = minutes;
            return this;
        }

        /**
         * @param minutes Specifies the target completion interval in minutes. (conflicts with `hours` and `seconds`)
         * 
         * @return builder
         * 
         */
        public Builder minutes(Integer minutes) {
            return minutes(Output.of(minutes));
        }

        /**
         * @param seconds Specifies the target completion interval in seconds. (conflicts with `hours` and `minutes`)
         * 
         * @return builder
         * 
         */
        public Builder seconds(@Nullable Output<Integer> seconds) {
            $.seconds = seconds;
            return this;
        }

        /**
         * @param seconds Specifies the target completion interval in seconds. (conflicts with `hours` and `minutes`)
         * 
         * @return builder
         * 
         */
        public Builder seconds(Integer seconds) {
            return seconds(Output.of(seconds));
        }

        public TaskTargetCompletionIntervalArgs build() {
            return $;
        }
    }

}
