// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Snowflake.Inputs
{

    public sealed class AuthenticationPolicyDescribeOutputGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("authenticationMethods")]
        public Input<string>? AuthenticationMethods { get; set; }

        [Input("clientTypes")]
        public Input<string>? ClientTypes { get; set; }

        [Input("comment")]
        public Input<string>? Comment { get; set; }

        [Input("mfaAuthenticationMethods")]
        public Input<string>? MfaAuthenticationMethods { get; set; }

        [Input("mfaEnrollment")]
        public Input<string>? MfaEnrollment { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("owner")]
        public Input<string>? Owner { get; set; }

        [Input("securityIntegrations")]
        public Input<string>? SecurityIntegrations { get; set; }

        public AuthenticationPolicyDescribeOutputGetArgs()
        {
        }
        public static new AuthenticationPolicyDescribeOutputGetArgs Empty => new AuthenticationPolicyDescribeOutputGetArgs();
    }
}
