// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Snowflake.Inputs
{

    public sealed class GetAuthenticationPoliciesOnInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Returns records for the entire account.
        /// </summary>
        [Input("account")]
        public Input<bool>? Account { get; set; }

        /// <summary>
        /// Returns records for the specified user.
        /// </summary>
        [Input("user")]
        public Input<string>? User { get; set; }

        public GetAuthenticationPoliciesOnInputArgs()
        {
        }
        public static new GetAuthenticationPoliciesOnInputArgs Empty => new GetAuthenticationPoliciesOnInputArgs();
    }
}
