// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Snowflake.Inputs
{

    public sealed class StageExternalS3FileFormatCsvGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defines the encoding format for binary input or output. Valid values: `HEX` | `BASE64` | `UTF8`.
        /// </summary>
        [Input("binaryFormat")]
        public Input<string>? BinaryFormat { get; set; }

        /// <summary>
        /// Specifies the compression format. Valid values: `AUTO` | `GZIP` | `BZ2` | `BROTLI` | `ZSTD` | `DEFLATE` | `RAW_DEFLATE` | `NONE`.
        /// </summary>
        [Input("compression")]
        public Input<string>? Compression { get; set; }

        /// <summary>
        /// Defines the format of date values in the data files. Use `AUTO` to have Snowflake auto-detect the format.
        /// </summary>
        [Input("dateFormat")]
        public Input<string>? DateFormat { get; set; }

        /// <summary>
        /// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`Default`)) Boolean that specifies whether to insert SQL NULL for empty fields in an input file. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
        /// </summary>
        [Input("emptyFieldAsNull")]
        public Input<string>? EmptyFieldAsNull { get; set; }

        /// <summary>
        /// Specifies the character set of the source data when loading data into a table. Valid values: `BIG5` | `EUCJP` | `EUCKR` | `GB18030` | `IBM420` | `IBM424` | `ISO2022CN` | `ISO2022JP` | `ISO2022KR` | `ISO88591` | `ISO88592` | `ISO88595` | `ISO88596` | `ISO88597` | `ISO88598` | `ISO88599` | `ISO885915` | `KOI8R` | `SHIFTJIS` | `UTF8` | `UTF16` | `UTF16BE` | `UTF16LE` | `UTF32` | `UTF32BE` | `UTF32LE` | `WINDOWS1250` | `WINDOWS1251` | `WINDOWS1252` | `WINDOWS1253` | `WINDOWS1254` | `WINDOWS1255` | `WINDOWS1256`.
        /// </summary>
        [Input("encoding")]
        public Input<string>? Encoding { get; set; }

        /// <summary>
        /// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`Default`)) Boolean that specifies whether to generate a parsing error if the number of delimited columns in an input file does not match the number of columns in the corresponding table. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
        /// </summary>
        [Input("errorOnColumnCountMismatch")]
        public Input<string>? ErrorOnColumnCountMismatch { get; set; }

        /// <summary>
        /// Single character string used as the escape character for field values. Use `NONE` to specify no escape character. NOTE: This value may be not imported properly from Snowflake. Snowflake returns escaped values.
        /// </summary>
        [Input("escape")]
        public Input<string>? Escape { get; set; }

        /// <summary>
        /// Single character string used as the escape character for unenclosed field values only. Use `NONE` to specify no escape character. NOTE: This value may be not imported properly from Snowflake. Snowflake returns escaped values.
        /// </summary>
        [Input("escapeUnenclosedField")]
        public Input<string>? EscapeUnenclosedField { get; set; }

        /// <summary>
        /// One or more singlebyte or multibyte characters that separate fields in an input file. Use `NONE` to specify no delimiter.
        /// </summary>
        [Input("fieldDelimiter")]
        public Input<string>? FieldDelimiter { get; set; }

        /// <summary>
        /// Character used to enclose strings. Use `NONE` to specify no enclosure character.
        /// </summary>
        [Input("fieldOptionallyEnclosedBy")]
        public Input<string>? FieldOptionallyEnclosedBy { get; set; }

        /// <summary>
        /// Specifies the extension for files unloaded to a stage.
        /// </summary>
        [Input("fileExtension")]
        public Input<string>? FileExtension { get; set; }

        /// <summary>
        /// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`Default`)) Boolean that specifies whether to parse CSV files containing multiple records on a single line. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
        /// </summary>
        [Input("multiLine")]
        public Input<string>? MultiLine { get; set; }

        [Input("nullIfs")]
        private InputList<string>? _nullIfs;

        /// <summary>
        /// String used to convert to and from SQL NULL.
        /// </summary>
        public InputList<string> NullIfs
        {
            get => _nullIfs ?? (_nullIfs = new InputList<string>());
            set => _nullIfs = value;
        }

        /// <summary>
        /// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`Default`)) Boolean that specifies whether to use the first row headers in the data files to determine column names. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
        /// </summary>
        [Input("parseHeader")]
        public Input<string>? ParseHeader { get; set; }

        /// <summary>
        /// One or more singlebyte or multibyte characters that separate records in an input file. Use `NONE` to specify no delimiter.
        /// </summary>
        [Input("recordDelimiter")]
        public Input<string>? RecordDelimiter { get; set; }

        /// <summary>
        /// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`Default`)) Boolean that specifies whether to replace invalid UTF-8 characters with the Unicode replacement character. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
        /// </summary>
        [Input("replaceInvalidCharacters")]
        public Input<string>? ReplaceInvalidCharacters { get; set; }

        /// <summary>
        /// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`Default`)) Boolean that specifies to skip any blank lines encountered in the data files. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
        /// </summary>
        [Input("skipBlankLines")]
        public Input<string>? SkipBlankLines { get; set; }

        /// <summary>
        /// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`Default`)) Boolean that specifies whether to skip the BOM (byte order mark) if present in a data file. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
        /// </summary>
        [Input("skipByteOrderMark")]
        public Input<string>? SkipByteOrderMark { get; set; }

        /// <summary>
        /// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`-1`)) Number of lines at the start of the file to skip.
        /// </summary>
        [Input("skipHeader")]
        public Input<int>? SkipHeader { get; set; }

        /// <summary>
        /// Defines the format of time values in the data files. Use `AUTO` to have Snowflake auto-detect the format.
        /// </summary>
        [Input("timeFormat")]
        public Input<string>? TimeFormat { get; set; }

        /// <summary>
        /// Defines the format of timestamp values in the data files. Use `AUTO` to have Snowflake auto-detect the format.
        /// </summary>
        [Input("timestampFormat")]
        public Input<string>? TimestampFormat { get; set; }

        /// <summary>
        /// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`Default`)) Boolean that specifies whether to remove white space from fields. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
        /// </summary>
        [Input("trimSpace")]
        public Input<string>? TrimSpace { get; set; }

        public StageExternalS3FileFormatCsvGetArgs()
        {
        }
        public static new StageExternalS3FileFormatCsvGetArgs Empty => new StageExternalS3FileFormatCsvGetArgs();
    }
}
