// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Snowflake.Inputs
{

    public sealed class StageExternalAzureShowOutputArgs : global::Pulumi.ResourceArgs
    {
        [Input("cloud")]
        public Input<string>? Cloud { get; set; }

        [Input("comment")]
        public Input<string>? Comment { get; set; }

        [Input("createdOn")]
        public Input<string>? CreatedOn { get; set; }

        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        [Input("directoryEnabled")]
        public Input<bool>? DirectoryEnabled { get; set; }

        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        [Input("hasCredentials")]
        public Input<bool>? HasCredentials { get; set; }

        [Input("hasEncryptionKey")]
        public Input<bool>? HasEncryptionKey { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("owner")]
        public Input<string>? Owner { get; set; }

        [Input("ownerRoleType")]
        public Input<string>? OwnerRoleType { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("schemaName")]
        public Input<string>? SchemaName { get; set; }

        [Input("storageIntegration")]
        public Input<string>? StorageIntegration { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("url")]
        public Input<string>? Url { get; set; }

        public StageExternalAzureShowOutputArgs()
        {
        }
        public static new StageExternalAzureShowOutputArgs Empty => new StageExternalAzureShowOutputArgs();
    }
}
