// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Snowflake.Inputs
{

    public sealed class StorageIntegrationDescribeOutputArgs : global::Pulumi.ResourceArgs
    {
        [Input("azureConsentUrls")]
        private InputList<Inputs.StorageIntegrationDescribeOutputAzureConsentUrlArgs>? _azureConsentUrls;
        public InputList<Inputs.StorageIntegrationDescribeOutputAzureConsentUrlArgs> AzureConsentUrls
        {
            get => _azureConsentUrls ?? (_azureConsentUrls = new InputList<Inputs.StorageIntegrationDescribeOutputAzureConsentUrlArgs>());
            set => _azureConsentUrls = value;
        }

        [Input("azureMultiTenantAppNames")]
        private InputList<Inputs.StorageIntegrationDescribeOutputAzureMultiTenantAppNameArgs>? _azureMultiTenantAppNames;
        public InputList<Inputs.StorageIntegrationDescribeOutputAzureMultiTenantAppNameArgs> AzureMultiTenantAppNames
        {
            get => _azureMultiTenantAppNames ?? (_azureMultiTenantAppNames = new InputList<Inputs.StorageIntegrationDescribeOutputAzureMultiTenantAppNameArgs>());
            set => _azureMultiTenantAppNames = value;
        }

        [Input("comments")]
        private InputList<Inputs.StorageIntegrationDescribeOutputCommentArgs>? _comments;
        public InputList<Inputs.StorageIntegrationDescribeOutputCommentArgs> Comments
        {
            get => _comments ?? (_comments = new InputList<Inputs.StorageIntegrationDescribeOutputCommentArgs>());
            set => _comments = value;
        }

        [Input("enableds")]
        private InputList<Inputs.StorageIntegrationDescribeOutputEnabledArgs>? _enableds;
        public InputList<Inputs.StorageIntegrationDescribeOutputEnabledArgs> Enableds
        {
            get => _enableds ?? (_enableds = new InputList<Inputs.StorageIntegrationDescribeOutputEnabledArgs>());
            set => _enableds = value;
        }

        [Input("storageAllowedLocations")]
        private InputList<Inputs.StorageIntegrationDescribeOutputStorageAllowedLocationArgs>? _storageAllowedLocations;
        public InputList<Inputs.StorageIntegrationDescribeOutputStorageAllowedLocationArgs> StorageAllowedLocations
        {
            get => _storageAllowedLocations ?? (_storageAllowedLocations = new InputList<Inputs.StorageIntegrationDescribeOutputStorageAllowedLocationArgs>());
            set => _storageAllowedLocations = value;
        }

        [Input("storageAwsExternalIds")]
        private InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsExternalIdArgs>? _storageAwsExternalIds;
        public InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsExternalIdArgs> StorageAwsExternalIds
        {
            get => _storageAwsExternalIds ?? (_storageAwsExternalIds = new InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsExternalIdArgs>());
            set => _storageAwsExternalIds = value;
        }

        [Input("storageAwsIamUserArns")]
        private InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsIamUserArnArgs>? _storageAwsIamUserArns;
        public InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsIamUserArnArgs> StorageAwsIamUserArns
        {
            get => _storageAwsIamUserArns ?? (_storageAwsIamUserArns = new InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsIamUserArnArgs>());
            set => _storageAwsIamUserArns = value;
        }

        [Input("storageAwsObjectAcls")]
        private InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsObjectAclArgs>? _storageAwsObjectAcls;
        public InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsObjectAclArgs> StorageAwsObjectAcls
        {
            get => _storageAwsObjectAcls ?? (_storageAwsObjectAcls = new InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsObjectAclArgs>());
            set => _storageAwsObjectAcls = value;
        }

        [Input("storageAwsRoleArns")]
        private InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsRoleArnArgs>? _storageAwsRoleArns;
        public InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsRoleArnArgs> StorageAwsRoleArns
        {
            get => _storageAwsRoleArns ?? (_storageAwsRoleArns = new InputList<Inputs.StorageIntegrationDescribeOutputStorageAwsRoleArnArgs>());
            set => _storageAwsRoleArns = value;
        }

        [Input("storageBlockedLocations")]
        private InputList<Inputs.StorageIntegrationDescribeOutputStorageBlockedLocationArgs>? _storageBlockedLocations;
        public InputList<Inputs.StorageIntegrationDescribeOutputStorageBlockedLocationArgs> StorageBlockedLocations
        {
            get => _storageBlockedLocations ?? (_storageBlockedLocations = new InputList<Inputs.StorageIntegrationDescribeOutputStorageBlockedLocationArgs>());
            set => _storageBlockedLocations = value;
        }

        [Input("storageGcpServiceAccounts")]
        private InputList<Inputs.StorageIntegrationDescribeOutputStorageGcpServiceAccountArgs>? _storageGcpServiceAccounts;
        public InputList<Inputs.StorageIntegrationDescribeOutputStorageGcpServiceAccountArgs> StorageGcpServiceAccounts
        {
            get => _storageGcpServiceAccounts ?? (_storageGcpServiceAccounts = new InputList<Inputs.StorageIntegrationDescribeOutputStorageGcpServiceAccountArgs>());
            set => _storageGcpServiceAccounts = value;
        }

        [Input("storageProviders")]
        private InputList<Inputs.StorageIntegrationDescribeOutputStorageProviderArgs>? _storageProviders;
        public InputList<Inputs.StorageIntegrationDescribeOutputStorageProviderArgs> StorageProviders
        {
            get => _storageProviders ?? (_storageProviders = new InputList<Inputs.StorageIntegrationDescribeOutputStorageProviderArgs>());
            set => _storageProviders = value;
        }

        [Input("usePrivatelinkEndpoints")]
        private InputList<Inputs.StorageIntegrationDescribeOutputUsePrivatelinkEndpointArgs>? _usePrivatelinkEndpoints;
        public InputList<Inputs.StorageIntegrationDescribeOutputUsePrivatelinkEndpointArgs> UsePrivatelinkEndpoints
        {
            get => _usePrivatelinkEndpoints ?? (_usePrivatelinkEndpoints = new InputList<Inputs.StorageIntegrationDescribeOutputUsePrivatelinkEndpointArgs>());
            set => _usePrivatelinkEndpoints = value;
        }

        public StorageIntegrationDescribeOutputArgs()
        {
        }
        public static new StorageIntegrationDescribeOutputArgs Empty => new StorageIntegrationDescribeOutputArgs();
    }
}
