// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as snowflake from "@pulumi/snowflake";
 *
 * const grant = new snowflake.AccountGrant("grant", {
 *     privilege: "CREATE ROLE",
 *     roles: [
 *         "role1",
 *         "role2",
 *     ],
 *     withGrantOption: false,
 * });
 * ```
 *
 * ## Import
 *
 * # format is account name | | | privilege | true/false for with_grant_option
 *
 * ```sh
 *  $ pulumi import snowflake:index/accountGrant:AccountGrant example 'accountName|||USAGE|true'
 * ```
 */
export class AccountGrant extends pulumi.CustomResource {
    /**
     * Get an existing AccountGrant resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AccountGrantState, opts?: pulumi.CustomResourceOptions): AccountGrant {
        return new AccountGrant(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'snowflake:index/accountGrant:AccountGrant';

    /**
     * Returns true if the given object is an instance of AccountGrant.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AccountGrant {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AccountGrant.__pulumiType;
    }

    /**
     * The privilege to grant on the account.
     */
    public readonly privilege!: pulumi.Output<string | undefined>;
    /**
     * Grants privilege to these roles.
     */
    public readonly roles!: pulumi.Output<string[] | undefined>;
    /**
     * When this is set to true, allows the recipient role to grant the privileges to other roles.
     */
    public readonly withGrantOption!: pulumi.Output<boolean | undefined>;

    /**
     * Create a AccountGrant resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AccountGrantArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccountGrantArgs | AccountGrantState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AccountGrantState | undefined;
            inputs["privilege"] = state ? state.privilege : undefined;
            inputs["roles"] = state ? state.roles : undefined;
            inputs["withGrantOption"] = state ? state.withGrantOption : undefined;
        } else {
            const args = argsOrState as AccountGrantArgs | undefined;
            inputs["privilege"] = args ? args.privilege : undefined;
            inputs["roles"] = args ? args.roles : undefined;
            inputs["withGrantOption"] = args ? args.withGrantOption : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(AccountGrant.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AccountGrant resources.
 */
export interface AccountGrantState {
    /**
     * The privilege to grant on the account.
     */
    privilege?: pulumi.Input<string>;
    /**
     * Grants privilege to these roles.
     */
    roles?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * When this is set to true, allows the recipient role to grant the privileges to other roles.
     */
    withGrantOption?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a AccountGrant resource.
 */
export interface AccountGrantArgs {
    /**
     * The privilege to grant on the account.
     */
    privilege?: pulumi.Input<string>;
    /**
     * Grants privilege to these roles.
     */
    roles?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * When this is set to true, allows the recipient role to grant the privileges to other roles.
     */
    withGrantOption?: pulumi.Input<boolean>;
}
